"""
Visualisation of the Asymmetric Driving Aggressiveness (ADA).

Produces four publication-ready figures:
  1) 3-D surface of the superposed ADA
  2) Filled-contour map with ego / agent patches and lane markings
  3) Per-agent ADA decomposition
  4) ADA intensity with negative-gradient quiver (risk-descent direction)
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.transforms as mtransforms
from ADA_config import ADAConfig as Cfg
from ADA import make_ego, make_agent, construct_ADA


# ── helper: rotated vehicle rectangle ─────────────────────────────────────
def _draw_vehicle(ax, veh, facecolor='grey', edgecolor='black', zorder=5):
    w, h = veh['length'], veh['width']
    angle_deg = np.degrees(veh['heading'])
    rect = mpatches.FancyBboxPatch(
        (-w / 2, -h / 2), w, h,
        boxstyle="round,pad=0.1",
        facecolor=facecolor, edgecolor=edgecolor, linewidth=1.0, zorder=zorder)
    t = (mtransforms.Affine2D()
         .rotate_deg(angle_deg)
         .translate(veh['x'], veh['y'])
         + ax.transData)
    rect.set_transform(t)
    ax.add_patch(rect)


def _draw_velocity_arrow(ax, veh, color='white', scale=0.4):
    dx = veh['vx'] * scale
    dy = veh['vy'] * scale
    ax.annotate('',
                xy=(veh['x'] + dx, veh['y'] + dy),
                xytext=(veh['x'], veh['y']),
                arrowprops=dict(arrowstyle='->', color=color,
                                lw=2, mutation_scale=15),
                zorder=6)


def _draw_lane_markings(ax, x_range, lane_centers, lane_width):
    y_bounds = sorted({c + s * lane_width / 2
                       for c in lane_centers for s in (-1, 1)})
    for i, yb in enumerate(y_bounds):
        style = '-w' if (i == 0 or i == len(y_bounds) - 1) else '--w'
        ax.plot(x_range, [yb, yb], style, linewidth=1.5, alpha=0.7)


def _speed_label(ax, veh, color='white'):
    ax.text(veh['x'] + veh['length'] / 2 + 1,
            veh['y'] + veh['width'] / 2 + 0.3,
            f"${veh['speed']:.0f}$ m/s",
            color=color, fontsize=10,
            bbox=dict(facecolor='black', alpha=0.4, boxstyle='round,pad=0.2'))


# ── colour palette for agents ─────────────────────────────────────────────
_AGENT_COLORS = ['#3498db', '#e67e22', '#2ecc71', '#9b59b6', '#e74c3c']
_EGO_COLOR = '#e74c3c'


# ── main demo ─────────────────────────────────────────────────────────────
def ADA_static_demo():
    """
    Reproduce the three-agent highway scenario.
    The ego vehicle perceives the Kinetic Wave Field generated by
    surrounding agents of different mass, speed, heading and acceleration.
    """
    plt.rcParams['font.family'] = 'serif'
    plt.rcParams['font.size'] = 12

    # ── Ego vehicle (risk receiver) ───────────────────────────────────────
    ego = make_ego(
        x=0, y=0, vx=25, vy=0, mass=7000,
        heading=0.0, accel=0.0,
        length=4.8, width=2.5, label='Ego')

    # ── Surrounding agents (wave sources) ─────────────────────────────────
    agent1 = make_agent(
        x=0, y=0, vx=23, vy=0, mass=15000,
        heading=0.0, accel=0.0,
        length=16.8, width=2.5, label='Agent 1 (Truck)')

    agent2 = make_agent(
        x=80, y=-4, vx=27 * np.cos(0.16), vy=27 * np.sin(0.16), mass=5000,
        heading=0.16, accel=2.0,
        length=13.8, width=2.5, label='Agent 2 (Truck)')

    agent3 = make_agent(
        x=120, y=4, vx=25, vy=0, mass=10000,
        heading=0.0, accel=0.0,
        length=4.8, width=2.2, label='Agent 3 (Car)')

    agents = [agent1, agent2, agent3]

    # Acceleration influence on effective speed  (v ← v + a·t₀)
    for v in agents:
        v['speed'] += v['accel'] * Cfg.t0
    ego['speed'] += ego['accel'] * Cfg.t0

    # ── Construct ADA ─────────────────────────────────────────────────────
    Xg, Yg = Cfg.X_mesh, Cfg.Y_mesh
    ADA_total, ADA_parts = construct_ADA(agents, ego, Xg, Yg)

    # ══════════════════════════════════════════════════════════════════════
    #  Figure 1 – 3-D surface
    # ══════════════════════════════════════════════════════════════════════
    fig1 = plt.figure(figsize=Cfg.figsize_3d)
    ax1 = fig1.add_subplot(111, projection='3d')
    step = max(1, int(1.0 / Cfg.resolution))
    ax1.plot_surface(Xg[::step, ::step], Yg[::step, ::step],
                     ADA_total[::step, ::step],
                     cmap=Cfg.cmap_name, edgecolor='none', alpha=0.9)
    ax1.set_xlabel('$x$ (m)')
    ax1.set_ylabel('$y$ (m)')
    ax1.set_zlabel('Risk intensity')
    ax1.set_title('Kinetic Wave Field – 3-D Surface')
    ax1.set_xlim(Cfg.x_min, Cfg.x_max)
    ax1.set_ylim(Cfg.y_min, Cfg.y_max)
    ax1.set_zlim(0, np.max(ADA_parts[0]) * 1.05)
    plt.tight_layout()

    # ══════════════════════════════════════════════════════════════════════
    #  Figure 2 – filled contour with vehicles
    # ══════════════════════════════════════════════════════════════════════
    fig2, ax2 = plt.subplots(figsize=Cfg.figsize_contour)

    cf = ax2.contourf(Xg, Yg, ADA_total,
                      levels=Cfg.contour_levels, cmap=Cfg.cmap_name, extend='both')
    ax2.contour(Xg, Yg, ADA_total,
                levels=Cfg.contour_levels, colors='k', linewidths=0.3, alpha=0.4)

    _draw_lane_markings(ax2, [Cfg.x_min, Cfg.x_max], [-4, 0, 4], Cfg.lane_width)

    for k, ag in enumerate(agents):
        _draw_vehicle(ax2, ag, facecolor=_AGENT_COLORS[k % len(_AGENT_COLORS)])
        _draw_velocity_arrow(ax2, ag, color='white')
        _speed_label(ax2, ag)

    cbar = plt.colorbar(cf, ax=ax2, pad=0.02, aspect=30)
    cbar.set_label('Risk intensity', fontsize=11)
    cbar.ax.set_yticklabels(['Low', '', '', '', '', '', 'High'])

    ax2.set_xlim(Cfg.x_min, Cfg.x_max)
    ax2.set_ylim(Cfg.y_min, Cfg.y_max)
    ax2.set_xlabel('$x$ (m)')
    ax2.set_ylabel('$y$ (m)')
    ax2.set_title('Kinetic Wave Field – Risk Map')
    ax2.set_aspect('auto')
    plt.tight_layout()

    # ══════════════════════════════════════════════════════════════════════
    #  Figure 3 – per-agent decomposition
    # ══════════════════════════════════════════════════════════════════════
    fig3, axes = plt.subplots(1, len(agents), figsize=(5 * len(agents), 3.5),
                              sharey=True)
    for k, (ax, kw_k) in enumerate(zip(axes, ADA_parts)):
        cf_k = ax.contourf(Xg, Yg, kw_k, levels=30, cmap=Cfg.cmap_name)
        _draw_vehicle(ax, agents[k],
                      facecolor=_AGENT_COLORS[k % len(_AGENT_COLORS)])
        _draw_lane_markings(ax, [Cfg.x_min, Cfg.x_max], [-4, 0, 4], Cfg.lane_width)
        ax.set_xlim(Cfg.x_min, Cfg.x_max)
        ax.set_ylim(Cfg.y_min, Cfg.y_max)
        ax.set_xlabel('$x$ (m)')
        ax.set_title(f'ADA from {agents[k]["label"]}')
        plt.colorbar(cf_k, ax=ax, pad=0.02)
    axes[0].set_ylabel('$y$ (m)')
    plt.tight_layout()

    # ══════════════════════════════════════════════════════════════════════
    #  Figure 4 – quiver (negative gradient = risk-descent direction)
    # ══════════════════════════════════════════════════════════════════════
    fig4, ax4 = plt.subplots(figsize=Cfg.figsize_contour)

    ax4.pcolormesh(Xg, Yg, ADA_total, cmap='jet', shading='gouraud')

    dy_step = Cfg.Y_[1] - Cfg.Y_[0]
    dx_step = Cfg.X_[1] - Cfg.X_[0]
    grad_y, grad_x = np.gradient(ADA_total, dy_step, dx_step)
    grad_mag = np.sqrt(grad_x ** 2 + grad_y ** 2) + 1e-12

    qs = max(1, int(3.0 / Cfg.resolution))
    ax4.quiver(Xg[::qs, ::qs], Yg[::qs, ::qs],
               -grad_x[::qs, ::qs] / grad_mag[::qs, ::qs],
               -grad_y[::qs, ::qs] / grad_mag[::qs, ::qs],
               color='white', alpha=0.6, scale=30)

    for k, ag in enumerate(agents):
        _draw_vehicle(ax4, ag, facecolor=_AGENT_COLORS[k % len(_AGENT_COLORS)])
        _draw_velocity_arrow(ax4, ag, color='yellow')

    _draw_lane_markings(ax4, [Cfg.x_min, Cfg.x_max], [-4, 0, 4], Cfg.lane_width)
    ax4.set_xlim(Cfg.x_min, Cfg.x_max)
    ax4.set_ylim(Cfg.y_min, Cfg.y_max)
    ax4.set_xlabel('$x$ (m)')
    ax4.set_ylabel('$y$ (m)')
    ax4.set_title('Kinetic Wave Field – Risk Gradient Quiver')
    plt.tight_layout()

    return fig1, fig2, fig3, fig4


# ── entry point ───────────────────────────────────────────────────────────
if __name__ == '__main__':
    figs = ADA_static_demo()
    for i, fig in enumerate(figs, 1):
        fig.savefig(f'ADA_fig{i}.png', dpi=200, bbox_inches='tight')
        print(f'Saved ADA_fig{i}.png')
    plt.show()
